"""Day20 barometer baseline — reference metrics for vio-check comparison.

Generated by running ``vio_check.baro_metrics_from_arrays`` (the exact core the
live ``vio-check`` uses) on all 7 Day20 flights, comparing ``/altimeter/range``
against ``/pf_geo_loc/fc_local_position`` (altair GT). These capture the
established Day20 barometer behaviour so a future bag can be compared against it.

Metrics per flight:
- ground_bias_m   : mean baro while on-ground (GPS) — the constant bias (→0 on ground)
- scale_pct       : altitude-proportional error (best-fit slope − 1), %
- noise_sigma_m   : high-frequency sensor noise σ (residual minus ~2 s rolling median)
- resid_sigma_m   : unexplained residual σ after bias+scale (the disturbance floor)
- spikes_pct      : % of flight that is a >3σ transient pressure disturbance
- pct_on_ground   : % of samples classified on-ground by GPS height

Regenerate after a method change with tools/gen_baro_baseline.py.
"""

from __future__ import annotations

DAY20_BARO_PER_FLIGHT: dict[str, dict[str, float]] = {
    'Day20.1': {'ground_bias_m': -0.308, 'scale_pct': 8.21, 'noise_sigma_m': 0.026, 'resid_sigma_m': 1.488, 'spikes_pct': 1.32, 'pct_on_ground': 17.2},
    'Day20.2': {'ground_bias_m': -0.274, 'scale_pct': 4.64, 'noise_sigma_m': 0.02,  'resid_sigma_m': 0.75,  'spikes_pct': 3.24, 'pct_on_ground': 20.8},
    'Day20.3': {'ground_bias_m': -0.208, 'scale_pct': 5.68, 'noise_sigma_m': 0.02,  'resid_sigma_m': 0.724, 'spikes_pct': 2.68, 'pct_on_ground': 10.0},
    'Day20.5': {'ground_bias_m': -0.025, 'scale_pct': 4.58, 'noise_sigma_m': 0.021, 'resid_sigma_m': 1.306, 'spikes_pct': 2.02, 'pct_on_ground': 15.4},
    'Day20.6': {'ground_bias_m': -0.123, 'scale_pct': 6.35, 'noise_sigma_m': 0.017, 'resid_sigma_m': 0.964, 'spikes_pct': 3.25, 'pct_on_ground': 7.9},
    'Day20.7': {'ground_bias_m': -0.243, 'scale_pct': 4.23, 'noise_sigma_m': 0.017, 'resid_sigma_m': 1.535, 'spikes_pct': 0.48, 'pct_on_ground': 8.8},
    'Day20.8': {'ground_bias_m':  0.053, 'scale_pct': 6.02, 'noise_sigma_m': 0.009, 'resid_sigma_m': 1.306, 'spikes_pct': 0.0,  'pct_on_ground': 10.5},
}

# Human label + format spec for each comparable metric.
BARO_METRICS: dict[str, tuple[str, str]] = {
    'ground_bias_m': ('ground bias',  '{:+.3f} m'),
    'scale_pct':     ('altitude scale', '{:+.2f} %'),
    'noise_sigma_m': ('HF noise σ',   '{:.3f} m'),
    'resid_sigma_m': ('residual σ',   '{:.3f} m'),
    'spikes_pct':    ('transients',   '{:.2f} %'),
    'pct_on_ground': ('on-ground',    '{:.1f} %'),
}


def _aggregate() -> dict[str, dict[str, float]]:
    import statistics as st
    out: dict[str, dict[str, float]] = {}
    for k in BARO_METRICS:
        vals = [v[k] for v in DAY20_BARO_PER_FLIGHT.values() if v.get(k) is not None]
        out[k] = {
            'mean': st.mean(vals),
            'min':  min(vals),
            'max':  max(vals),
            'std':  st.pstdev(vals) if len(vals) > 1 else 0.0,
            'n':    len(vals),
        }
    return out


# Aggregate (mean / min / max / std) across the Day20 flights, computed at import.
DAY20_BARO_AGG: dict[str, dict[str, float]] = _aggregate()
